/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EE333;

/**
 *
 * @author Brooks
 */
public class ContactInfoJpanel extends javax.swing.JPanel {
    
    private EE333.ContactInfo contactInfo = new EE333.ContactInfo();
    
    public EE333.ContactInfo getContactInfo() {
        return( this.contactInfo );
    }
    
    public void setContactInfo( EE333.ContactInfo contactInfo ) {
        this.contactInfo = contactInfo;
    }

    /**
     * Creates new form ContactInfoJpanel
     */
    public ContactInfoJpanel() {
        initComponents();
        
        java.io.File InputFile;
        java.io.FileReader InputFileReader;
        java.io.BufferedReader InputBufferedReader;
        String line = "";
        
        this.JComboState.removeAllItems();
        try {
            InputFile = new java.io.File("States.txt");
            if ( InputFile.exists() == true ) {
                InputFileReader = new java.io.FileReader(InputFile);
                InputBufferedReader = new java.io.BufferedReader(InputFileReader);
                
                while (( line = InputBufferedReader.readLine() ) != null ) {
                    this.JComboState.addItem(line);
                }
                
                InputBufferedReader.close();
                
            } else {
                System.out.println("Error: No States.txt provided!");
                // throw new java.lang.Exception("Error: No States.txt provided!");
            }
        } catch (java.lang.Exception ex) {
            System.out.println( ex.toString() );
        }
    }
    
    public boolean updateControls() {
        boolean results = true;
        
        // take the values from the contact info to update
        //      the GUI controls
        this.JTextAddress.setText( this.contactInfo.getAddress() );
        this.JTextCity.setText( this.contactInfo.getCity() );
        this.JComboState.setSelectedItem( this.contactInfo.getState() );
        this.JTextZip.setText( this.contactInfo.getZip() );
        this.JTextEmail.setText( this.contactInfo.getEmail() );
        this.JTextPhoneNumber.setText( this.contactInfo.getPhoneNumber());
        
        return( results );
    }
    
    public boolean updateUnderlyingObject() {
        boolean results = true;
        
        // needs validation
        
        this.contactInfo.setAddress( this.JTextAddress.getText() );
        this.contactInfo.setCity( this.JTextCity.getText() );
        this.contactInfo.setState( this.JComboState.getSelectedItem().toString() ); // note: explicitly uses the .tostring of the object
        this.contactInfo.setZip( this.JTextZip.getText() );
        this.contactInfo.setEmail( this.JTextEmail.getText() );
        this.contactInfo.setPhoneNumber( this.JTextPhoneNumber.getText() );
        
        return( results );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTextAddress = new javax.swing.JTextField();
        JTextCity = new javax.swing.JTextField();
        JTextZip = new javax.swing.JTextField();
        JTextEmail = new javax.swing.JTextField();
        JTextPhoneNumber = new javax.swing.JTextField();
        JComboState = new javax.swing.JComboBox<>();

        jLabel1.setText("Address");

        jLabel2.setText("City");

        jLabel3.setText("State");

        jLabel4.setText("Zip");

        jLabel5.setText("Email");

        jLabel6.setText("PhoneNumber");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextPhoneNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextZip))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JComboState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextCity))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(JComboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTextZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTextPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboState;
    private javax.swing.JTextField JTextAddress;
    private javax.swing.JTextField JTextCity;
    private javax.swing.JTextField JTextEmail;
    private javax.swing.JTextField JTextPhoneNumber;
    private javax.swing.JTextField JTextZip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
