/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EE333;

/**
 *
 * @author Brooks
 */
public class CycleJPanel extends javax.swing.JPanel {
    
    private EE333.Cycle cycle;
    private int wheelCount;
    private EE333.Vehicle tempVehicle;

    /**
     * Creates new form CycleJPanel
     */
    public CycleJPanel() {
        initComponents();
    }
    
    public int getWheelCount() {
        return( this.wheelCount );
    }
    
    public void setWheelCount(int wheelCount) {
        this.wheelCount = wheelCount;
    }
    
    public EE333.Vehicle getTempVehicle() {
        return ( this.tempVehicle );
    }
    
    public boolean updateControls() {
        boolean results = true;
        
        this.jTextWheelCount.setText( String.valueOf(this.cycle.getWheelCount()) );
        
        return( results );
    }
    
    public boolean updateControls( EE333.Cycle tempCycle) {
        boolean results = true;
        
        this.cycle = tempCycle;
        
        this.jTextWheelCount.setText( String.valueOf(this.cycle.getWheelCount()) );
        
        return( results );
    }
    
    public boolean updateUnderlyingObject() {
        boolean results = true;
        
//        this.wheelCount = 
        
        this.setWheelCount(Integer.parseInt( jTextWheelCount.getText() ));
//        this.cycle = new Cycle(tempVehicle, wheelCount);
        
        return( results );
    }
    
    public boolean updateUnderlyingObject( EE333.Vehicle tempVehicle ) {
        boolean results = true;
        
//        this.wheelCount = 
        
        this.setWheelCount(Integer.parseInt( jTextWheelCount.getText() ));
        this.cycle = new Cycle(tempVehicle, wheelCount);
        
        return( results );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelWheelCount = new javax.swing.JLabel();
        jTextWheelCount = new javax.swing.JTextField();

        jLabel1.setText("Cycle");

        jLabelWheelCount.setText("WheelCount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelWheelCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextWheelCount, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWheelCount)
                    .addComponent(jTextWheelCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelWheelCount;
    private javax.swing.JTextField jTextWheelCount;
    // End of variables declaration//GEN-END:variables

    /**
     * @param wheelCount the wheelCount to set
     */
    
}
