/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EE333;

/**
 *
 * @author Brooks
 */
public class InsuranceJPanel extends javax.swing.JPanel {

    private EE333.InsuranceInfo insuranceInfo;
    
    public EE333.InsuranceInfo getInsuranceInfo() {
        return( this.insuranceInfo );
    }
    
    public void setInsuranceInfo( EE333.InsuranceInfo insuranceInfo ) {
        this.insuranceInfo = insuranceInfo;
    }
    
    /**
     * Creates new form InsuranceJPanel
     */
    public InsuranceJPanel() {
        initComponents();
    }
    
    public boolean importCustom( java.io.File customFile ) {
        // accept a .user file
        boolean results = true;
        String contents = "";
        
        contents = importString(customFile);
        if (contents == "" ) {
            // this means no string was found ( or no file was found )
            results = false;
        } else {
            // we want to parse the contents of the file...
            if (importCustom(contents) == false) {
                results = false;
            } else {
                results = true; // we need to update our GUI (potentially)
            }
        }
        
        return( results );
    } 
    
    public boolean importCustom( String customString ) {
        boolean results = true;
        
        this.insuranceInfo = EE333.InsuranceInfo.importCustom(customString);
        
        if(this.insuranceInfo == new EE333.InsuranceInfo() ) {
            
            this.jTextPolicyNumber.setText("");
            this.jTextExpirationDate.setText("");
            this.jTextFirstname.setText("");
            this.jTextLastname.setText("");
            
            results = false;
        } else {
//             we need to update our GUI...
            this.jTextPolicyNumber.setText( this.insuranceInfo.getPolicyNumber() );
            this.jTextExpirationDate.setText( this.insuranceInfo.getExpirationDate() );
            this.jTextFirstname.setText( this.insuranceInfo.getFirstName() );
            this.jTextLastname.setText( this.insuranceInfo.getLastName() );
            
            results = true;
        }
        
        return( results );
    }
    
    private String importString( java.io.File inputFile ) {
        String results = "";
        String line = "";
        java.io.FileReader inputFileReader;
        java.io.BufferedReader inputBufferedReader;       
        
        try {
            if (inputFile.exists() == true) {
                inputFileReader = new java.io.FileReader(inputFile);
                inputBufferedReader = new java.io.BufferedReader(inputFileReader);
                
                while ((line = inputBufferedReader.readLine()) != null) {
                    results += line + '\n'; // appends the contents line by line.
                }
                
                inputBufferedReader.close();
            } else {
                results = "";
            }
        } catch (java.lang.Exception ex) {
            System.out.println( ex.toString() );
        }
        
        return( results );
    } 
    
    public boolean updateControls() {
        boolean results = true;
        
        this.jTextPolicyNumber.setText( this.insuranceInfo.getPolicyNumber() );
        this.jTextExpirationDate.setText( this.insuranceInfo.getExpirationDate() );
        this.jTextFirstname.setText( this.insuranceInfo.getFirstName() );
        this.jTextLastname.setText( this.insuranceInfo.getLastName() );
        
        return( results );
    }
    
    public boolean updateUnderlyingObject() {
        boolean results = true;
        
        // need a way to set the policynumber without a setter
        this.insuranceInfo = new InsuranceInfo( jTextPolicyNumber.getText(), jTextExpirationDate.getText(), jTextFirstname.getText(), jTextLastname.getText() );
//        this.insuranceInfo.setExpirationDate( this.jTextExpirationDate.getText() );
//        this.insuranceInfo.setFirstName( this.jTextFirstname.getText() );
//        this.insuranceInfo.setLastName( this.jTextLastname.getText() );
        
        return( results );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextExpirationDate = new javax.swing.JTextField();
        jTextPolicyNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFirstname = new javax.swing.JTextField();
        jTextLastname = new javax.swing.JTextField();

        jLabel1.setText("Insurance");

        jLabel2.setText("policyNumber");

        jLabel3.setText("expirationDate");

        jTextExpirationDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExpirationDateActionPerformed(evt);
            }
        });

        jLabel4.setText("Firstname");

        jLabel5.setText("Lastname");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jTextPolicyNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jTextFirstname)
                    .addComponent(jTextLastname))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextExpirationDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExpirationDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExpirationDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextExpirationDate;
    private javax.swing.JTextField jTextFirstname;
    private javax.swing.JTextField jTextLastname;
    private javax.swing.JTextField jTextPolicyNumber;
    // End of variables declaration//GEN-END:variables
}
