/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EE333;

/**
 *
 * @author Brooks
 */
public class RegistrationInfoJPanel extends javax.swing.JPanel {

    private EE333.RegistrationInfo registrationInfo = new EE333.RegistrationInfo();
    
    
    public EE333.RegistrationInfo getRegistrationInfo() {
        return( this.registrationInfo );
    }
    
    public void setRegistrationInfo( EE333.RegistrationInfo registrationInfo ) {
        this.registrationInfo = registrationInfo;
    }
    
    /**
     * Creates new form RegistrationInfoJPanel
     */
    public RegistrationInfoJPanel() {
        initComponents();
    }
    public boolean importCustom( java.io.File customFile ) {
        // accept a .user file
        boolean results = true;
        String contents = "";
        
        contents = importString(customFile);
        if (contents == "" ) {
            // this means no string was found ( or no file was found )
            results = false;
        } else {
            // we want to parse the contents of the file...
            if (importCustom(contents) == false) {
                results = false;
            } else {
                results = true; // we need to update our GUI (potentially)
            }
        }
        
        return( results );
    } 
    
    public boolean importCustom( String customString ) {
        boolean results = true;
        
        this.registrationInfo = EE333.RegistrationInfo.importCustom(customString);
        
        if ( this.registrationInfo == new EE333.RegistrationInfo() ) {
            this.jTextFieldRegID.setText("");
            this.jTextFieldPolicyNumber.setText("");
            this.jTextFieldVIN.setText("");
            this.jTextTagExpires.setText("");
            this.jTextTagNumber.setText("");
            this.jTextSalesTax.setText("0.0");
            this.jTextAdValTax.setText("0.0");
        } else {
            this.jTextFieldRegID.setText(this.registrationInfo.getRegID());
            this.jTextFieldPolicyNumber.setText(this.registrationInfo.getPolicyNumber());
            this.jTextFieldVIN.setText(this.registrationInfo.getVIN());
            this.jTextTagExpires.setText(this.registrationInfo.getTagExpires());
            this.jTextTagNumber.setText(this.registrationInfo.getTagNumber());
            this.jTextSalesTax.setText(String.valueOf(this.registrationInfo.getSalesTax()));
            this.jTextAdValTax.setText(String.valueOf(this.registrationInfo.getAdValTax()));
        }
        
        return( results );
    }
    
    private String importString( java.io.File inputFile ) {
        String results = "";
        String line = "";
        java.io.FileReader inputFileReader;
        java.io.BufferedReader inputBufferedReader;       
        
        try {
            if (inputFile.exists() == true) {
                inputFileReader = new java.io.FileReader(inputFile);
                inputBufferedReader = new java.io.BufferedReader(inputFileReader);
                
                while ((line = inputBufferedReader.readLine()) != null) {
                    results += line + '\n'; // appends the contents line by line.
                }
                
                inputBufferedReader.close();
            } else {
                results = "";
            }
        } catch (java.lang.Exception ex) {
            System.out.println( ex.toString() );
        }
        
        return( results );
    } 
    
    public boolean updateControls() {
        boolean results = true;
        
        this.jTextTagExpires.setText( this.registrationInfo.getTagExpires() );
        this.jTextTagNumber.setText( this.registrationInfo.getTagNumber() );
        this.jTextSalesTax.setText( String.valueOf( this.registrationInfo.getSalesTax() ));
        this.jTextAdValTax.setText( String.valueOf( this.registrationInfo.getAdValTax() ));
        
        return( results );
    }
    
    public boolean updateUnderlyingObject() {
        boolean results = true;
        
        this.registrationInfo = new RegistrationInfo(jTextFieldRegID.getText(), jTextFieldPolicyNumber.getText(), jTextFieldVIN.getText(), jTextTagExpires.getText(), jTextTagNumber.getText(), Double.parseDouble(jTextSalesTax.getText()), Double.parseDouble(jTextAdValTax.getText()));

        return( results );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextTagExpires = new javax.swing.JTextField();
        jTextTagNumber = new javax.swing.JTextField();
        jTextSalesTax = new javax.swing.JTextField();
        jTextAdValTax = new javax.swing.JTextField();
        jLabelRegID = new javax.swing.JLabel();
        jLabelPolicyNumber = new javax.swing.JLabel();
        jLabelVIN = new javax.swing.JLabel();
        jTextFieldRegID = new javax.swing.JTextField();
        jTextFieldPolicyNumber = new javax.swing.JTextField();
        jTextFieldVIN = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        jLabel1.setText("RegistrationInfo");

        jLabel2.setText("TagExpires");

        jLabel3.setText("TagNumber");

        jLabel4.setText("SalesTax");

        jLabel5.setText("adValTax");

        jLabelRegID.setText("regID");

        jLabelPolicyNumber.setText("policyNumber");

        jLabelVIN.setText("VIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelVIN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPolicyNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRegID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldVIN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextTagExpires, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(jTextFieldRegID)
                                        .addComponent(jTextFieldPolicyNumber))
                                    .addComponent(jTextAdValTax, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextTagNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextSalesTax, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPolicyNumber)
                    .addComponent(jTextFieldPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVIN)
                    .addComponent(jTextFieldVIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextTagExpires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextTagNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextSalesTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextAdValTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPolicyNumber;
    private javax.swing.JLabel jLabelRegID;
    private javax.swing.JLabel jLabelVIN;
    private javax.swing.JTextField jTextAdValTax;
    private javax.swing.JTextField jTextFieldPolicyNumber;
    private javax.swing.JTextField jTextFieldRegID;
    private javax.swing.JTextField jTextFieldVIN;
    private javax.swing.JTextField jTextSalesTax;
    private javax.swing.JTextField jTextTagExpires;
    private javax.swing.JTextField jTextTagNumber;
    // End of variables declaration//GEN-END:variables
}
