/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EE333;

/**
 *
 * @author Brooks
 */
public class TruckJPanel extends javax.swing.JPanel {

    private int wheelCount;
    private int doorCount;
    private int payload;
    private EE333.Truck truck;
    
    public EE333.Truck getTruck() {
        return( this.truck );
    }
    
    public int getWheelCount() {
        return( this.wheelCount );
    }
    
    public void setWheelCount(int wheelCount) {
        this.wheelCount = wheelCount;
    }
    
    /**
     * @return the doorCount
     */
    public int getDoorCount() {
        return doorCount;
    }

    /**
     * @param doorCount the doorCount to set
     */
    public void setDoorCount(int doorCount) {
        this.doorCount = doorCount;
    }
    
    /**
     * @return the payload
     */
    public int getPayload() {
        return payload;
    }

    /**
     * @param payload the payload to set
     */
    public void setPayload(int payload) {
        this.payload = payload;
    }
    
    /**
     * Creates new form TruckJPanel
     */
    public TruckJPanel() {
        initComponents();
    }
    
    public boolean updateControls() {
        boolean results = true;
        
        this.jTextDoorCount.setText( String.valueOf(this.truck.getDoorCount()) );
        this.jTextWheelCount.setText( String.valueOf(this.truck.getWheelCount()) );
        this.jTextPayload.setText( String.valueOf(this.truck.getPayload()) );
        
        return( results );
    }
    
    public boolean updateControls(EE333.Truck tempTruck) {
        boolean results = true;
        
        this.truck = tempTruck;
        
        this.jTextDoorCount.setText( String.valueOf(this.truck.getDoorCount()) );
        this.jTextWheelCount.setText( String.valueOf(this.truck.getWheelCount()) );
        this.jTextPayload.setText( String.valueOf(this.truck.getPayload()) );
        
        return( results );
    }
    
    public boolean updateUnderlyingObject() {
        boolean results = true;
        
        this.setWheelCount(Integer.parseInt( jTextWheelCount.getText() ));
        this.setDoorCount(Integer.parseInt( jTextDoorCount.getText() ));
        this.setPayload(Integer.parseInt( jTextPayload.getText() ));
        
        
        return( results );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextWheelCount = new javax.swing.JTextField();
        jTextPayload = new javax.swing.JTextField();
        jTextDoorCount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("WheelCount");

        jLabel2.setText("DoorCount");

        jLabel3.setText("Payload");

        jTextDoorCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDoorCountActionPerformed(evt);
            }
        });

        jLabel4.setText("Truck");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextWheelCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextDoorCount, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextPayload, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextWheelCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextDoorCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextPayload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDoorCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDoorCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDoorCountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextDoorCount;
    private javax.swing.JTextField jTextPayload;
    private javax.swing.JTextField jTextWheelCount;
    // End of variables declaration//GEN-END:variables

    
}
